function ensureAdvancedData(){
  data.approvals??=[];
  data.refunds??=[];
  data.medicines.forEach(m=>{m.dispenseUnit??=m.unit||"盒";m.conversion??=1;m.location??="药房默认库位";m.publicVisible??=false});
  data.suppliers.forEach(s=>{s.licenseNo??="";s.licenseExpiry??=""});
  data.prescriptions.forEach(p=>{if(!p.items)p.items=[{medicineId:p.medicineId,medicineName:p.medicineName,quantity:p.quantity,unit:byId(p.medicineId)?.unit||"盒",amount:p.amount}];p.status??="已收费"});
}
ensureAdvancedData();save();
const approvalStatus=x=>x.status==="待审核"?["待审核","risk-orange"]:x.status==="已通过"?["已通过","risk-green"]:["已驳回","risk-red"];
function addApproval(type,detail,payload={}){data.approvals.unshift({id:"sh"+Date.now()+Math.random(),date:new Date().toISOString(),type,detail,payload,submitter:currentUser().name,status:"待审核"});save()}
function renderApprovals(){const pending=data.approvals.filter(x=>x.status==="待审核").length;document.getElementById("approvalCount").textContent=pending;document.getElementById("approvalTable").innerHTML=data.approvals.map(x=>`<tr><td>${fmtTime(x.date)}</td><td>${x.type}</td><td>${x.detail}</td><td>${x.submitter}</td><td>${badge(approvalStatus(x))}</td><td>${x.status==="待审核"?`<button class="link-btn" data-approve="${x.id}">通过</button> · <button class="link-btn" data-reject="${x.id}">驳回</button>`:x.reviewer||"-"}</td></tr>`).join("")||empty(6)}
function renderPublicMedicines(){document.getElementById("publicMedicineTable").innerHTML=data.medicines.map(m=>{const active=(m.batches||[]).filter(b=>b.quantity>0&&days(b)>=0).sort((a,b)=>new Date(a.expiryDate)-new Date(b.expiryDate))[0];return `<tr><td>${drug(m)}</td><td>${total(m)} ${m.unit}</td><td>${active?active.expiryDate:"无可售批次"}</td><td>${xMoney(m.salePrice)}</td><td>${badge(m.publicVisible?["公开展示","risk-green"]:["仅内部可见","risk-orange"])}</td><td><button class="link-btn" data-public-edit="${m.id}">设置价格与公开状态</button></td></tr>`}).join("")||empty(6)}
function medicineOptionHtml(){return data.medicines.filter(m=>!m.disabled&&total(m)>0).map(m=>`<option value="${m.id}">${m.name}（库存 ${total(m)} ${m.unit}）</option>`).join("")}
function addPrescriptionItemRow(){const row=document.createElement("div");row.className="prescription-row";row.innerHTML=`<select name="itemMedicine" required>${medicineOptionHtml()}</select><input name="itemQuantity" type="number" min="1" value="1" required placeholder="数量"><input name="itemAmount" type="number" min="0" step="0.01" value="0" required placeholder="金额"><button type="button" class="link-btn" data-remove-item>移除</button>`;document.getElementById("prescriptionItems").appendChild(row)}
function renderPrescriptionItems(){const box=document.getElementById("prescriptionItems");box.innerHTML="";addPrescriptionItemRow()}
renderPrescriptions=function(){const revenue=data.prescriptions.filter(x=>x.status!=="已退款").reduce((s,x)=>s+Number(x.amount),0);document.getElementById("financeStats").innerHTML=[["处方数量",data.prescriptions.length,"张"],["收费总额",xMoney(revenue),"扣除退款后"],["待审核",data.approvals.filter(x=>x.status==="待审核").length,"项"],["患者人数",new Set(data.prescriptions.map(x=>x.patient)).size,"人"]].map(x=>`<div class="stat-card"><div class="stat-top"><span>${x[0]}</span></div><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join("");document.getElementById("prescriptionTable").innerHTML=data.prescriptions.map(x=>`<tr><td>${fmtTime(x.date)}</td><td>${x.id}</td><td>${x.patient}</td><td>${x.doctor}</td><td>${x.items.map(i=>`${i.medicineName} × ${i.quantity}`).join("<br>")}</td><td>${xMoney(x.amount)}</td><td>${badge([x.status,x.status==="已退款"?"risk-red":x.status==="退款审核中"?"risk-orange":"risk-green"])}</td><td>${x.status==="已收费"?`<button class="link-btn" data-refund="${x.id}">申请退药退款</button>`:"-"}</td></tr>`).join("")||empty(8)}
renderPurchases=function(){document.getElementById("purchaseSupplier").innerHTML=data.suppliers.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");document.getElementById("purchaseMedicine").innerHTML=data.medicines.filter(m=>!m.disabled).map(m=>`<option value="${m.id}">${m.name}</option>`).join("");document.getElementById("supplierList").innerHTML=data.suppliers.map(x=>{const expired=x.licenseExpiry&&new Date(x.licenseExpiry)<new Date();return `<div class="mini-item"><div><strong>${x.name}</strong><small>${x.contact||"未填写联系人"} ${x.phone||""}</small><small>资质：${x.licenseNo||"未登记"} ${x.licenseExpiry?`· 至 ${x.licenseExpiry}`:""}</small></div>${badge(expired?["资质已过期","risk-red"]:x.licenseExpiry?["资质有效","risk-green"]:["待补资料","risk-orange"])}</div>`}).join("")||'<div class="empty">暂无供应商</div>';const lows=data.medicines.filter(m=>!m.disabled&&total(m)<=m.minStock);document.getElementById("reorderList").innerHTML=lows.map(m=>`<div class="mini-item"><div><strong>${m.name}</strong><small>当前 ${total(m)} ${m.unit} · 预警值 ${m.minStock} · ${m.location}</small></div><span class="risk risk-orange">建议补 ${Math.max(m.minStock*2-total(m),m.minStock)} ${m.unit}</span></div>`).join("")||'<div class="empty">当前无需补货</div>';document.getElementById("purchaseTable").innerHTML=data.purchases.map(x=>`<tr><td>${fmtTime(x.date)}</td><td>${x.supplierName}</td><td>${x.medicineName}</td><td>${x.batchNo}</td><td>${x.quantity}</td><td>${xMoney(x.cost)}</td><td>${x.operator}</td></tr>`).join("")||empty(7)}
renderMedicines=function(){const rows=filtered(data.medicines).map(m=>`<tr><td>${drug(m)}<span class="permission-tag">${m.location}</span>${m.barcode?` <span class="permission-tag">条码 ${m.barcode}</span>`:""}</td><td>${m.category}</td><td>${m.spec}<br><small>${m.conversion>1?`1 ${m.unit} = ${m.conversion} ${m.dispenseUnit}`:m.unit}</small></td><td><strong>${total(m)}</strong> ${m.unit}</td><td>${m.batches.length}</td><td>${badge(m.disabled?["已停用","risk-red"]:medStatus(m))}</td><td>${can("medicine.edit")?`<button class="link-btn" data-edit-medicine="${m.id}">编辑</button> · <button class="link-btn" data-toggle-medicine="${m.id}">${m.disabled?"启用":"停用"}</button>${currentUser().role==="admin"?` · <button class="link-btn danger-link" data-delete-medicine="${m.id}">删除</button>`:""}`:""}${!m.disabled&&canAny("stock.in,stock.out")?`${can("medicine.edit")?" · ":""}<button class="link-btn" data-stock="${m.id}">出入库</button>`:""}</td></tr>`).join("");document.getElementById("medicineTable").innerHTML=rows||empty(7)}
const advBaseRender=render;
render=function(){ensureAdvancedData();advBaseRender();renderApprovals();renderPrescriptions();renderPurchases();renderMedicines();renderPublicMedicines()};
const advBaseSwitchPage=switchPage;
switchPage=function(id){if(id==="approvals"&&currentUser().role!=="admin")return toast("仅管理员可以进入审核中心");if(id==="publicManage"&&!requirePermission("public.manage"))return;advBaseSwitchPage(id);if(id==="approvals"&&document.getElementById(id).classList.contains("active")){document.getElementById("pageTitle").textContent="审核中心";document.getElementById("pageSubtitle").textContent="复核库存差异、报损销毁和退药退款"}if(id==="publicManage"&&document.getElementById(id).classList.contains("active")){document.getElementById("pageTitle").textContent="对外药品管理";document.getElementById("pageSubtitle").textContent="设置顾客窗口可见药品与零售价"}};
document.getElementById("addPrescriptionItem").onclick=addPrescriptionItemRow;
function processApproval(x,approved){
  x.status=approved?"已通过":"已驳回";x.reviewer=currentUser().name;
  if(approved&&x.type==="库存盘点差异"){const y=xByBatchKey(x.payload.batchKey),diff=+x.payload.actual-y.batch.quantity;y.batch.quantity=+x.payload.actual;data.operations.unshift({type:"count",date:new Date().toISOString(),medicineName:y.medicine.name,batchNo:y.batch.batchNo,diff,note:x.payload.note,operator:x.submitter})}
  if(approved&&x.type==="报损销毁"){const y=xByBatchKey(x.payload.batchKey),q=+x.payload.quantity;if(y.batch.quantity>=q){y.batch.quantity-=q;data.operations.unshift({type:"disposal",date:new Date().toISOString(),medicineName:y.medicine.name,batchNo:y.batch.batchNo,quantity:q,reason:x.payload.reason,note:x.payload.note,operator:x.submitter})}else toast("库存已变化，请重新提交报损申请")}
  if(x.type==="退药退款"){const p=data.prescriptions.find(p=>p.id===x.payload.prescriptionId);if(approved){p.status="已退款";p.items.forEach(i=>{const m=byId(i.medicineId);(i.allocations||[{batchNo:m.batches[0]?.batchNo,quantity:i.quantity}]).forEach(a=>{const batch=m.batches.find(b=>b.batchNo===a.batchNo);if(batch){batch.quantity+=a.quantity;data.transactions.unshift({id:"t"+Date.now()+m.id+a.batchNo,date:new Date().toISOString(),medicineId:m.id,batchNo:batch.batchNo,type:"in",quantity:a.quantity,balance:batch.quantity,operator:currentUser().name,note:"退药退款回库"})}})})}else p.status="已收费"}
  audit(approved?"审核通过":"审核驳回",`${x.type} · ${x.detail}`);save();render();toast("审核结果已保存")
}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.removeItem){if(document.querySelectorAll(".prescription-row").length>1)b.closest(".prescription-row").remove();else toast("处方至少保留一种药品")}if(b.dataset.open==="prescriptionModal")renderPrescriptionItems();if(b.dataset.refund){const p=data.prescriptions.find(x=>x.id===b.dataset.refund);if(confirm(`确认提交 ${p.id} 的退药退款申请吗？`)){p.status="退款审核中";addApproval("退药退款",`${p.id} · ${p.patient} · ${xMoney(p.amount)}`,{prescriptionId:p.id});audit("提交退款申请",p.id);save();render();toast("退款申请已提交审核")}}if(b.dataset.approve||b.dataset.reject){if(!requirePermission("users.manage"))return;processApproval(data.approvals.find(a=>a.id===(b.dataset.approve||b.dataset.reject)),!!b.dataset.approve)}});
document.getElementById("prescriptionForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("prescription.create"))return;const base=Object.fromEntries(new FormData(e.target)),meds=[...e.target.querySelectorAll('[name="itemMedicine"]')],qtys=[...e.target.querySelectorAll('[name="itemQuantity"]')],amounts=[...e.target.querySelectorAll('[name="itemAmount"]')],items=meds.map((x,i)=>({medicineId:x.value,medicineName:byId(x.value).name,quantity:+qtys[i].value,amount:+amounts[i].value,unit:byId(x.value).unit,allocations:[]}));if(items.some(i=>total(byId(i.medicineId))<i.quantity))return toast("有药品库存不足，无法完成发药");items.forEach(i=>{const m=byId(i.medicineId);let left=i.quantity;[...m.batches].sort((a,b)=>new Date(a.expiryDate)-new Date(b.expiryDate)).forEach(batch=>{if(!left||!batch.quantity)return;const take=Math.min(left,batch.quantity);batch.quantity-=take;left-=take;i.allocations.push({batchNo:batch.batchNo,quantity:take});data.transactions.unshift({id:"t"+Date.now()+batch.batchNo,date:new Date().toISOString(),medicineId:m.id,batchNo:batch.batchNo,type:"out",quantity:take,balance:batch.quantity,operator:currentUser().name,note:"处方发药"})})});const id="CF-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+String(data.prescriptions.length+1).padStart(3,"0"),amount=items.reduce((s,i)=>s+i.amount,0);data.prescriptions.unshift({id,date:new Date().toISOString(),patient:base.patient,doctor:base.doctor,payment:base.payment,items,amount,status:"已收费"});audit("处方收费",`${id}，${base.patient}，${items.length} 种药品，${xMoney(amount)}`);save();render();closeModals();e.target.reset();toast("处方已收费并完成发药")};
const advEditSubmit=document.getElementById("editMedicineForm").onsubmit;
document.getElementById("editMedicineForm").onsubmit=e=>{const v=Object.fromEntries(new FormData(e.target)),m=byId(v.medicineId);if(m)Object.assign(m,{dispenseUnit:v.dispenseUnit||v.unit,conversion:+v.conversion||1,location:v.location||"药房默认库位",publicVisible:v.publicVisible==="true"});advEditSubmit.call(e.target,e)};
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||!b.dataset.editMedicine)return;const m=byId(b.dataset.editMedicine),form=document.getElementById("editMedicineForm");form.elements.dispenseUnit.value=m.dispenseUnit;form.elements.conversion.value=m.conversion;form.elements.location.value=m.location;form.elements.publicVisible.value=String(m.publicVisible)});
document.getElementById("supplierForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("purchase.manage"))return;const v=Object.fromEntries(new FormData(e.target));data.suppliers.push({id:"s"+Date.now(),...v});audit("新增供应商",`${v.name} · 资质 ${v.licenseNo||"未登记"}`);save();render();closeModals();e.target.reset();toast("供应商已保存")};
document.getElementById("openPublicCatalog").onclick=()=>window.open("catalog.html","clinic-public-catalog");
document.getElementById("previewPublicCatalog").onclick=()=>window.open("catalog.html","clinic-public-catalog");
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||!b.dataset.publicEdit)return;if(!requirePermission("public.manage"))return;const m=byId(b.dataset.publicEdit),form=document.getElementById("publicMedicineForm");form.elements.medicineId.value=m.id;form.elements.medicineName.value=m.name;form.elements.salePrice.value=m.salePrice;form.elements.publicVisible.value=String(m.publicVisible);openModal("publicMedicineModal")});
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b||!b.dataset.deleteMedicine)return;if(currentUser().role!=="admin")return toast("仅管理员可以永久删除药品");const m=byId(b.dataset.deleteMedicine),hasHistory=total(m)>0||data.transactions.some(x=>x.medicineId===m.id)||data.purchases.some(x=>x.medicineName===m.name)||data.prescriptions.some(x=>(x.items||[]).some(i=>i.medicineId===m.id))||data.operations.some(x=>x.medicineName===m.name);if(hasHistory)return toast("该药品已有库存或业务记录，请使用停用保留历史");if(!confirm(`确认永久删除“${m.name}”吗？此操作无法撤销。`))return;audit("永久删除药品",`${m.name} · ${m.code}`);data.medicines=data.medicines.filter(x=>x.id!==m.id);save();render();toast("药品已永久删除")});
document.getElementById("publicMedicineForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("public.manage"))return;const v=Object.fromEntries(new FormData(e.target)),m=byId(v.medicineId);m.salePrice=+v.salePrice;m.publicVisible=v.publicVisible==="true";audit("设置对外药品",`${m.name} · ${xMoney(m.salePrice)} · ${m.publicVisible?"公开":"隐藏"}`);save();render();closeModals();toast("对外药品设置已保存")};
document.getElementById("countForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("inventory.count"))return;const v=Object.fromEntries(new FormData(e.target)),x=xByBatchKey(v.batchKey),diff=+v.actual-x.batch.quantity;if(!diff)return toast("实际库存与系统库存一致，无需调整");addApproval("库存盘点差异",`${x.medicine.name} ${x.batch.batchNo} · 差异 ${diff}`,v);audit("提交盘点审核",`${x.medicine.name} ${x.batch.batchNo} · 差异 ${diff}`);closeModals();e.target.reset();toast("盘点差异已提交审核")};
document.getElementById("disposalForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("disposal.create"))return;const v=Object.fromEntries(new FormData(e.target)),x=xByBatchKey(v.batchKey),q=+v.quantity;if(q>x.batch.quantity)return toast("下架数量不能超过当前库存");addApproval("报损销毁",`${x.medicine.name} ${x.batch.batchNo} · ${v.reason} ${v.quantity}`,v);audit("提交报损审核",`${x.medicine.name} ${x.batch.batchNo} · ${v.reason} ${v.quantity}`);closeModals();e.target.reset();toast("报损申请已提交审核")};
render();
