const DAY=86400000,storeKey="qinghe-clinic-pharmacy-v1";
const iso=d=>d.toISOString().slice(0,10),offset=n=>iso(new Date(Date.now()+n*DAY));
const demo={medicines:[
{id:"m1",name:"阿莫西林胶囊",code:"YP-001",category:"西药",spec:"0.25g × 24粒",manufacturer:"华北制药",minStock:40,batches:[{batchNo:"AMX250301",productionDate:"2025-03-01",expiryDate:offset(18),quantity:26},{batchNo:"AMX251001",productionDate:"2025-10-01",expiryDate:offset(310),quantity:64}]},
{id:"m2",name:"布洛芬缓释胶囊",code:"YP-002",category:"西药",spec:"0.3g × 20粒",manufacturer:"珠海联邦",minStock:35,batches:[{batchNo:"BLF240620",productionDate:"2024-06-20",expiryDate:offset(-9),quantity:12},{batchNo:"BLF251220",productionDate:"2025-12-20",expiryDate:offset(190),quantity:42}]},
{id:"m3",name:"复方氨酚烷胺片",code:"YP-003",category:"西药",spec:"12片 / 盒",manufacturer:"感康药业",minStock:25,batches:[{batchNo:"GKA250716",productionDate:"2025-07-16",expiryDate:offset(62),quantity:18}]},
{id:"m4",name:"碘伏消毒液",code:"YP-004",category:"外用药",spec:"100ml / 瓶",manufacturer:"利尔康",minStock:20,batches:[{batchNo:"DFX260205",productionDate:"2026-02-05",expiryDate:offset(355),quantity:48}]},
{id:"m5",name:"医用外科口罩",code:"HC-001",category:"医疗耗材",spec:"10只 / 包",manufacturer:"稳健医疗",minStock:30,batches:[{batchNo:"KZ260101",productionDate:"2026-01-01",expiryDate:offset(800),quantity:120}]},
{id:"m6",name:"藿香正气口服液",code:"YP-005",category:"中成药",spec:"10ml × 10支",manufacturer:"太极集团",minStock:20,batches:[{batchNo:"HX250922",productionDate:"2025-09-22",expiryDate:offset(27),quantity:14}]}
],transactions:[]};
demo.transactions=[
{id:"t1",date:new Date(Date.now()-55*60000).toISOString(),medicineId:"m1",batchNo:"AMX251001",type:"out",quantity:6,balance:64,operator:"药房管理员",note:"门诊发药"},
{id:"t2",date:new Date(Date.now()-125*60000).toISOString(),medicineId:"m4",batchNo:"DFX260205",type:"in",quantity:48,balance:48,operator:"药房管理员",note:"常规采购入库"},
{id:"t3",date:new Date(Date.now()-DAY).toISOString(),medicineId:"m6",batchNo:"HX250922",type:"out",quantity:3,balance:14,operator:"药房管理员",note:"门诊发药"},
{id:"t4",date:new Date(Date.now()-2*DAY).toISOString(),medicineId:"m5",batchNo:"KZ260101",type:"in",quantity:120,balance:120,operator:"药房管理员",note:"耗材补充"}];
let data=load(),inventoryFilter="all",alertFilter="all",transactionFilter="all",query="";
function load(){try{return JSON.parse(localStorage.getItem(storeKey))||structuredClone(demo)}catch{return structuredClone(demo)}}
function save(){localStorage.setItem(storeKey,JSON.stringify(data))}
const byId=id=>data.medicines.find(m=>m.id===id),total=m=>m.batches.reduce((s,b)=>s+b.quantity,0),days=b=>Math.ceil((new Date(b.expiryDate+"T23:59:59")-Date.now())/DAY);
function batchStatus(b){const d=days(b);return d<0?["已过期","risk-red"]:d<=30?["紧急临期","risk-red"]:d<=90?["临期","risk-orange"]:["正常","risk-green"]}
function medStatus(m){const t=total(m);return t===0?["无库存","risk-red"]:t<=m.minStock?["库存不足","risk-orange"]:["库存正常","risk-green"]}
const fmtDate=s=>new Date(s).toLocaleDateString("zh-CN"),fmtTime=s=>new Date(s).toLocaleString("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});
const badge=([a,b])=>`<span class="risk ${b}">${a}</span>`,drug=m=>`<div class="drug-name"><strong>${m.name}</strong><span>${m.code} · ${m.spec}</span></div>`;
function allBatches(){return data.medicines.flatMap(m=>m.batches.map(b=>({...b,medicine:m})))}
function filtered(items){if(!query)return items;const q=query.toLowerCase();return items.filter(x=>JSON.stringify(x).toLowerCase().includes(q))}
function render(){
 const batches=allBatches(), alerts=batches.filter(b=>days(b)<=90&&b.quantity>0), lows=data.medicines.filter(m=>total(m)<=m.minStock), healthy=data.medicines.filter(m=>total(m)>m.minStock).length;
 document.getElementById("navAlertCount").textContent=alerts.length;
 document.getElementById("heroActionCount").textContent=alerts.length+lows.length;
 document.getElementById("statsGrid").innerHTML=[
 ["药品品种",data.medicines.length,"种已录入","▤","#e3f5f0","#087f68"],["库存总量",batches.reduce((s,b)=>s+b.quantity,0),"件 / 盒 / 瓶","□","#e8f0fb","#4f87d9"],["效期预警",alerts.length,"个批次需关注","!","#fff0dc","#ed8d36"],["库存不足",lows.length,"种药品待补充","↓","#fee7e6","#df5a58"]
 ].map(x=>`<div class="stat-card"><div class="stat-top"><span>${x[0]}</span><i class="stat-icon" style="background:${x[4]};color:${x[5]}">${x[3]}</i></div><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join("");
 renderDashboard(alerts,healthy);renderMedicines();renderInventory();renderAlerts();renderTransactions();renderSelect();
}
function renderDashboard(alerts,healthy){
 const items=[...alerts].sort((a,b)=>days(a)-days(b)).slice(0,4);
 document.getElementById("dashboardAlerts").innerHTML=items.map(b=>`<div class="alert-item"><i class="alert-dot" style="background:${days(b)<=30?"#df5a58":"#ed8d36"}"></i><div class="alert-main"><strong>${b.medicine.name}</strong><span>批号 ${b.batchNo} · ${b.expiryDate}</span></div>${badge(batchStatus(b))}</div>`).join("")||'<div class="empty">暂无效期提醒</div>';
 const rate=data.medicines.length?Math.round(healthy/data.medicines.length*100):0,low=data.medicines.filter(m=>total(m)<=m.minStock).length;
 document.getElementById("healthRate").textContent=rate+"%";document.getElementById("donut").style.background=`conic-gradient(var(--green) 0 ${rate}%,var(--orange) ${rate}% ${Math.min(rate+Math.round(low/data.medicines.length*100),100)}%,var(--red) 0)`;
 document.getElementById("inventoryLegend").innerHTML=`<p><i style="background:#087f68"></i>库存充足 ${healthy} 种</p><p><i style="background:#ed8d36"></i>库存不足 ${low} 种</p><p><i style="background:#df5a58"></i>无库存 ${data.medicines.filter(m=>!total(m)).length} 种</p>`;
 document.getElementById("recentTransactions").innerHTML=transactionRows(data.transactions.slice(0,5),false);
}
function renderMedicines(){const rows=filtered(data.medicines).map(m=>`<tr><td>${drug(m)}</td><td>${m.category}</td><td>${m.spec}</td><td><strong>${total(m)}</strong></td><td>${m.batches.length}</td><td>${badge(medStatus(m))}</td><td><button class="link-btn" data-stock="${m.id}">登记出入库</button></td></tr>`).join("");document.getElementById("medicineTable").innerHTML=rows||empty(7)}
function renderInventory(){let items=allBatches();if(inventoryFilter==="low")items=items.filter(b=>total(b.medicine)<=b.medicine.minStock);if(inventoryFilter==="expiring")items=items.filter(b=>days(b)<=90);items=filtered(items);document.getElementById("inventoryTable").innerHTML=items.sort((a,b)=>days(a)-days(b)).map(b=>`<tr><td>${drug(b.medicine)}</td><td>${b.batchNo}</td><td>${b.productionDate}</td><td>${b.expiryDate}</td><td>${days(b)<0?`已过期 ${Math.abs(days(b))} 天`:`${days(b)} 天`}</td><td><strong>${b.quantity}</strong></td><td>${badge(batchStatus(b))}</td></tr>`).join("")||empty(7)}
function renderAlerts(){let items=allBatches().filter(b=>days(b)<=90&&b.quantity>0);if(alertFilter==="expired")items=items.filter(b=>days(b)<0);if(alertFilter==="urgent")items=items.filter(b=>days(b)>=0&&days(b)<=30);if(alertFilter==="soon")items=items.filter(b=>days(b)>30);document.getElementById("alertTable").innerHTML=items.sort((a,b)=>days(a)-days(b)).map(b=>`<tr><td>${badge(batchStatus(b))}</td><td>${drug(b.medicine)}</td><td>${b.batchNo}</td><td>${b.expiryDate}</td><td>${days(b)<0?`已过期 ${-days(b)} 天`:`${days(b)} 天`}</td><td>${b.quantity}</td><td>${days(b)<0?"立即下架并登记处理":"优先使用，暂停继续采购"}</td></tr>`).join("")||empty(7)}
function transactionRows(items,full=true){return filtered(items).map(t=>{const m=byId(t.medicineId);return `<tr><td>${fmtTime(t.date)}</td><td>${m?m.name:"已删除药品"}</td><td>${t.batchNo}</td><td>${badge([t.type==="in"?"入库":"出库",t.type==="in"?"risk-green":"risk-orange"])}</td><td class="quantity ${t.type}">${t.type==="in"?"+":"-"}${t.quantity}</td>${full?`<td>${t.balance}</td>`:""}<td>${t.operator}</td>${full?`<td>${t.note||"-"}</td>`:""}</tr>`}).join("")}
function renderTransactions(){let items=data.transactions;if(transactionFilter!=="all")items=items.filter(t=>t.type===transactionFilter);document.getElementById("transactionTable").innerHTML=transactionRows(items)||empty(8)}
function renderSelect(){document.getElementById("stockMedicine").innerHTML=data.medicines.map(m=>`<option value="${m.id}">${m.name}（库存 ${total(m)}）</option>`).join("")}
const empty=n=>`<tr><td colspan="${n}" class="empty">暂无符合条件的数据</td></tr>`;
function openModal(id,medicineId){document.getElementById(id).classList.add("open");document.getElementById("modalBackdrop").classList.add("open");if(medicineId)document.getElementById("stockMedicine").value=medicineId}
function closeModals(){document.querySelectorAll(".modal,.modal-backdrop").forEach(x=>x.classList.remove("open"))}
function toast(s){const e=document.getElementById("toast");e.textContent=s;e.style.display="block";setTimeout(()=>e.style.display="none",2200)}
function switchPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav-item[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===id));const meta={dashboard:["工作台","掌握库存状态，优先处理风险事项"],medicines:["药品档案","维护诊所药品基础信息"],inventory:["库存管理","按批次查看库存与有效期"],alerts:["效期预警","及时处理过期与临期药品"],transactions:["出入库记录","追踪每一次库存变动"]}[id];document.getElementById("pageTitle").textContent=meta[0];document.getElementById("pageSubtitle").textContent=meta[1]}
document.addEventListener("click",e=>{const t=e.target.closest("button");if(!t)return;if(t.dataset.page)switchPage(t.dataset.page);if(t.dataset.pageLink)switchPage(t.dataset.pageLink);if(t.dataset.open)openModal(t.dataset.open);if(t.dataset.close!==undefined)closeModals();if(t.dataset.stock)openModal("stockModal",t.dataset.stock);if(t.dataset.inventoryFilter){inventoryFilter=t.dataset.inventoryFilter;document.querySelectorAll("[data-inventory-filter]").forEach(x=>x.classList.toggle("active",x===t));renderInventory()}if(t.dataset.alertFilter){alertFilter=t.dataset.alertFilter;document.querySelectorAll("[data-alert-filter]").forEach(x=>x.classList.toggle("active",x===t));renderAlerts()}if(t.dataset.transactionFilter){transactionFilter=t.dataset.transactionFilter;document.querySelectorAll("[data-transaction-filter]").forEach(x=>x.classList.toggle("active",x===t));renderTransactions()}});
document.getElementById("modalBackdrop").onclick=closeModals;
document.getElementById("globalSearch").oninput=e=>{query=e.target.value.trim();renderMedicines();renderInventory();renderTransactions()};
document.querySelectorAll('input[name="type"]').forEach(x=>x.onchange=()=>document.getElementById("batchFields").style.display=x.value==="in"&&x.checked?"block":"none");
document.getElementById("medicineForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),v=Object.fromEntries(f);if(new Date(v.expiryDate)<=new Date(v.productionDate))return toast("有效期必须晚于生产日期");const m={id:crypto.randomUUID(),name:v.name,code:v.code,barcode:v.barcode||"",category:v.category,spec:v.spec,unit:v.unit||"盒",manufacturer:v.manufacturer,minStock:+v.minStock,salePrice:+v.salePrice||0,batches:[{batchNo:v.batchNo,productionDate:v.productionDate,expiryDate:v.expiryDate,quantity:+v.quantity}]};data.medicines.push(m);data.transactions.unshift({id:"t"+Date.now(),date:new Date().toISOString(),medicineId:m.id,batchNo:v.batchNo,type:"in",quantity:+v.quantity,balance:+v.quantity,operator:"药房管理员",note:"首次录入"});save();render();e.target.reset();closeModals();toast("药品录入成功")};
document.getElementById("stockForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),v=Object.fromEntries(f),m=byId(v.medicineId),q=+v.quantity;if(v.type==="in"){if(!v.batchNo||!v.productionDate||!v.expiryDate)return toast("请完整填写入库批次信息");if(new Date(v.expiryDate)<=new Date(v.productionDate))return toast("有效期必须晚于生产日期");let b=m.batches.find(x=>x.batchNo===v.batchNo);if(b)b.quantity+=q;else{b={batchNo:v.batchNo,productionDate:v.productionDate,expiryDate:v.expiryDate,quantity:q};m.batches.push(b)}data.transactions.unshift({id:"t"+Date.now(),date:new Date().toISOString(),medicineId:m.id,batchNo:b.batchNo,type:"in",quantity:q,balance:b.quantity,operator:"药房管理员",note:v.note||"采购入库"})}else{if(total(m)<q)return toast("库存不足，无法完成出库");let left=q;[...m.batches].sort((a,b)=>new Date(a.expiryDate)-new Date(b.expiryDate)).forEach(b=>{if(!left||!b.quantity)return;const take=Math.min(left,b.quantity);b.quantity-=take;left-=take;data.transactions.unshift({id:"t"+Date.now()+b.batchNo,date:new Date().toISOString(),medicineId:m.id,batchNo:b.batchNo,type:"out",quantity:take,balance:b.quantity,operator:"药房管理员",note:v.note||"门诊发药"})})}save();render();e.target.reset();document.getElementById("batchFields").style.display="block";closeModals();toast(v.type==="in"?"入库登记成功":"出库登记成功")};
document.getElementById("resetDemo").onclick=()=>{if(confirm("确定恢复演示数据吗？当前录入内容将被替换。")){data=structuredClone(demo);save();render();toast("已恢复演示数据")}};
document.getElementById("todayText").textContent=new Date().toLocaleDateString("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"short"});
render();
