function ensureExtendedData(){
  data.operations??=[];
  data.suppliers??=[{id:"s-default",name:"常用医药供应商",contact:"采购联系人",phone:"",note:"演示供应商"}];
  data.purchases??=[];
  data.prescriptions??=[];
  data.audit??=[];
  data.settings??={expiryWarningDays:90,backupReminder:true};
  data.medicines.forEach(m=>{m.unit??="盒";m.barcode??="";m.salePrice??=0;m.warningDays??=data.settings.expiryWarningDays;m.disabled??=false});
}
ensureExtendedData();save();
const xByBatchKey=key=>{const [medicineId,batchNo]=key.split("::"),medicine=byId(medicineId);return {medicine,batch:medicine&&medicine.batches.find(b=>b.batchNo===batchNo)}};
const xBatchOptions=()=>allBatches().filter(b=>b.quantity>0).map(b=>`<option value="${b.medicine.id}::${b.batchNo}">${b.medicine.name} · ${b.batchNo}（库存 ${b.quantity}）</option>`).join("");
const xMoney=n=>"￥"+Number(n||0).toFixed(2);
function audit(action,detail){ensureExtendedData();data.audit.unshift({id:"a"+Date.now()+Math.random(),date:new Date().toISOString(),operator:currentUser().name,action,detail});save()}
function renderOperations(){document.getElementById("countBatch").innerHTML=xBatchOptions();document.getElementById("disposalBatch").innerHTML=xBatchOptions();document.getElementById("operationTable").innerHTML=data.operations.map(x=>`<tr><td>${fmtTime(x.date)}</td><td>${badge([x.type==="count"?"库存盘点":"报损下架",x.type==="count"?"risk-green":"risk-orange"])}</td><td>${x.medicineName}</td><td>${x.batchNo}</td><td>${x.type==="count"?(x.diff>0?"+":"")+x.diff:"-"+x.quantity}</td><td>${x.reason||x.note||"-"}</td><td>${x.operator}</td></tr>`).join("")||empty(7)}
function renderPurchases(){document.getElementById("purchaseSupplier").innerHTML=data.suppliers.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");document.getElementById("purchaseMedicine").innerHTML=data.medicines.filter(m=>!m.disabled).map(m=>`<option value="${m.id}">${m.name}</option>`).join("");document.getElementById("supplierList").innerHTML=data.suppliers.map(x=>`<div class="mini-item"><div><strong>${x.name}</strong><small>${x.contact||"未填写联系人"} ${x.phone||""}</small></div></div>`).join("")||'<div class="empty">暂无供应商</div>';const lows=data.medicines.filter(m=>!m.disabled&&total(m)<=m.minStock);document.getElementById("reorderList").innerHTML=lows.map(m=>`<div class="mini-item"><div><strong>${m.name}</strong><small>当前 ${total(m)} · 预警值 ${m.minStock}</small></div><span class="risk risk-orange">建议补 ${Math.max(m.minStock*2-total(m),m.minStock)}</span></div>`).join("")||'<div class="empty">当前无需补货</div>';document.getElementById("purchaseTable").innerHTML=data.purchases.map(x=>`<tr><td>${fmtTime(x.date)}</td><td>${x.supplierName}</td><td>${x.medicineName}</td><td>${x.batchNo}</td><td>${x.quantity}</td><td>${xMoney(x.cost)}</td><td>${x.operator}</td></tr>`).join("")||empty(7)}
function renderPrescriptions(){document.getElementById("prescriptionMedicine").innerHTML=data.medicines.filter(m=>!m.disabled&&total(m)>0).map(m=>`<option value="${m.id}">${m.name}（库存 ${total(m)}）</option>`).join("");const revenue=data.prescriptions.reduce((s,x)=>s+Number(x.amount),0);document.getElementById("financeStats").innerHTML=[["处方数量",data.prescriptions.length,"张"],["收费总额",xMoney(revenue),"累计收入"],["今日处方",data.prescriptions.filter(x=>new Date(x.date).toDateString()===new Date().toDateString()).length,"张"],["患者人数",new Set(data.prescriptions.map(x=>x.patient)).size,"人"]].map(x=>`<div class="stat-card"><div class="stat-top"><span>${x[0]}</span></div><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join("");document.getElementById("prescriptionTable").innerHTML=data.prescriptions.map(x=>`<tr><td>${fmtTime(x.date)}</td><td>${x.id}</td><td>${x.patient}</td><td>${x.doctor}</td><td>${x.medicineName}</td><td>${x.quantity}</td><td>${xMoney(x.amount)}</td><td>${badge(["已收费","risk-green"])}</td></tr>`).join("")||empty(8)}
function renderAudit(){document.getElementById("auditTable").innerHTML=data.audit.map(x=>`<tr><td>${fmtTime(x.date)}</td><td>${x.operator}</td><td>${x.action}</td><td>${x.detail}</td></tr>`).join("")||empty(4)}
renderMedicines=function(){const rows=filtered(data.medicines).map(m=>`<tr><td>${drug(m)}<span class="permission-tag">${m.unit}</span>${m.barcode?` <span class="permission-tag">条码 ${m.barcode}</span>`:""}</td><td>${m.category}</td><td>${m.spec}</td><td><strong>${total(m)}</strong></td><td>${m.batches.length}</td><td>${badge(m.disabled?["已停用","risk-red"]:medStatus(m))}</td><td>${can("medicine.create")?`<button class="link-btn" data-edit-medicine="${m.id}">编辑</button> · <button class="link-btn" data-toggle-medicine="${m.id}">${m.disabled?"启用":"停用"}</button>`:""}${!m.disabled&&canAny("stock.in,stock.out")?`${can("medicine.create")?" · ":""}<button class="link-btn" data-stock="${m.id}">出入库</button>`:""}</td></tr>`).join("");document.getElementById("medicineTable").innerHTML=rows||empty(7)}
function extendedAlerts(){return allBatches().filter(b=>days(b)<=(b.medicine.warningDays||data.settings.expiryWarningDays)&&b.quantity>0)}
renderAlerts=function(){let items=extendedAlerts();if(alertFilter==="expired")items=items.filter(b=>days(b)<0);if(alertFilter==="urgent")items=items.filter(b=>days(b)>=0&&days(b)<=30);if(alertFilter==="soon")items=items.filter(b=>days(b)>30);document.getElementById("alertTable").innerHTML=items.sort((a,b)=>days(a)-days(b)).map(b=>`<tr><td>${badge(batchStatus(b))}</td><td>${drug(b.medicine)}</td><td>${b.batchNo}</td><td>${b.expiryDate}</td><td>${days(b)<0?`已过期 ${-days(b)} 天`:`${days(b)} 天`}</td><td>${b.quantity}</td><td>${days(b)<0?"立即下架并登记处理":"优先使用，暂停继续采购"}</td></tr>`).join("")||empty(7)}
function renderExtendedAlerts(){const alerts=extendedAlerts(),healthy=data.medicines.filter(m=>total(m)>m.minStock).length,lows=data.medicines.filter(m=>total(m)<=m.minStock);document.getElementById("navAlertCount").textContent=alerts.length;document.getElementById("heroActionCount").textContent=alerts.length+lows.length;const cards=document.getElementById("statsGrid").children;if(cards[2])cards[2].querySelector("strong").textContent=alerts.length;renderDashboard(alerts,healthy);renderAlerts()}
const xBaseRender=render;
render=function(){ensureExtendedData();xBaseRender();renderOperations();renderPurchases();renderPrescriptions();renderAudit();renderExtendedAlerts()};
const xBaseSwitchPage=switchPage;
switchPage=function(id){if(id==="operations"&&!canAny("inventory.count,disposal.create"))return toast("当前用户没有库存管理权限");if(id==="purchases"&&!requirePermission("purchase.manage"))return;if(id==="prescriptions"&&!requirePermission("prescription.create"))return;if(id==="reports"&&!requirePermission("reports.export"))return;if(id==="audit"&&!requirePermission("users.manage"))return;xBaseSwitchPage(id);const meta={operations:["盘点与报损","处理账实差异、过期药品和异常库存"],purchases:["采购与供应商","维护采购来源并及时补充库存"],prescriptions:["处方与收费","记录患者发药与收费明细"],reports:["报表与备份","导出数据并保护业务资料"],audit:["审计日志","追踪重要操作与权限变更"]}[id];if(meta&&document.getElementById(id).classList.contains("active")){document.getElementById("pageTitle").textContent=meta[0];document.getElementById("pageSubtitle").textContent=meta[1]}};
document.getElementById("countForm").onsubmit=e=>{e.preventDefault();if(!canAny("stock.in,stock.out"))return toast("当前用户没有库存管理权限");const v=Object.fromEntries(new FormData(e.target)),x=xByBatchKey(v.batchKey),actual=+v.actual,diff=actual-x.batch.quantity;x.batch.quantity=actual;data.operations.unshift({type:"count",date:new Date().toISOString(),medicineName:x.medicine.name,batchNo:x.batch.batchNo,diff,note:v.note,operator:currentUser().name});audit("库存盘点",`${x.medicine.name} ${x.batch.batchNo}，差异 ${diff}`);save();render();closeModals();e.target.reset();toast("盘点已完成")};
document.getElementById("disposalForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("stock.out"))return;const v=Object.fromEntries(new FormData(e.target)),x=xByBatchKey(v.batchKey),q=+v.quantity;if(q>x.batch.quantity)return toast("下架数量不能超过当前库存");x.batch.quantity-=q;data.operations.unshift({type:"disposal",date:new Date().toISOString(),medicineName:x.medicine.name,batchNo:x.batch.batchNo,quantity:q,reason:v.reason,note:v.note,operator:currentUser().name});audit("报损下架",`${x.medicine.name} ${x.batch.batchNo}，${v.reason} ${q}`);save();render();closeModals();e.target.reset();toast("报损下架已登记")};
document.getElementById("supplierForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("purchase.manage"))return;const v=Object.fromEntries(new FormData(e.target));data.suppliers.push({id:"s"+Date.now(),...v});audit("新增供应商",v.name);save();render();closeModals();e.target.reset();toast("供应商已保存")};
document.getElementById("purchaseForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("purchase.manage"))return;const v=Object.fromEntries(new FormData(e.target)),m=byId(v.medicineId),s=data.suppliers.find(x=>x.id===v.supplierId),q=+v.quantity;if(new Date(v.expiryDate)<=new Date(v.productionDate))return toast("有效期必须晚于生产日期");let b=m.batches.find(x=>x.batchNo===v.batchNo);if(b)b.quantity+=q;else m.batches.push({batchNo:v.batchNo,productionDate:v.productionDate,expiryDate:v.expiryDate,quantity:q});data.purchases.unshift({id:"p"+Date.now(),date:new Date().toISOString(),supplierName:s.name,medicineName:m.name,batchNo:v.batchNo,quantity:q,cost:+v.cost,operator:currentUser().name});data.transactions.unshift({id:"t"+Date.now(),date:new Date().toISOString(),medicineId:m.id,batchNo:v.batchNo,type:"in",quantity:q,balance:b?b.quantity:q,operator:currentUser().name,note:"采购入库"});audit("采购入库",`${m.name} ${v.batchNo}，数量 ${q}`);save();render();closeModals();e.target.reset();toast("采购入库成功")};
document.getElementById("prescriptionForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("prescription.create"))return;const v=Object.fromEntries(new FormData(e.target)),m=byId(v.medicineId),q=+v.quantity;if(total(m)<q)return toast("药品库存不足");let left=q;[...m.batches].sort((a,b)=>new Date(a.expiryDate)-new Date(b.expiryDate)).forEach(b=>{if(!left||!b.quantity)return;const take=Math.min(left,b.quantity);b.quantity-=take;left-=take;data.transactions.unshift({id:"t"+Date.now()+b.batchNo,date:new Date().toISOString(),medicineId:m.id,batchNo:b.batchNo,type:"out",quantity:take,balance:b.quantity,operator:currentUser().name,note:"处方发药"})});const id="CF-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+String(data.prescriptions.length+1).padStart(3,"0");data.prescriptions.unshift({id,date:new Date().toISOString(),patient:v.patient,doctor:v.doctor,medicineName:m.name,medicineId:m.id,quantity:q,amount:+v.amount,payment:v.payment});audit("处方收费",`${id}，患者 ${v.patient}，${m.name} ${q}`);save();render();closeModals();e.target.reset();toast("处方已收费并完成发药")};
function download(name,content,type="text/csv;charset=utf-8"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
const csv=rows=>rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.export==="inventory")download("库存报表.csv",csv([["药品","编码","批号","有效期","库存","状态"],...allBatches().map(x=>[x.medicine.name,x.medicine.code,x.batchNo,x.expiryDate,x.quantity,batchStatus(x)[0]])]));if(b.dataset.export==="transactions")download("出入库流水.csv",csv([["时间","药品","批号","类型","数量","操作人","备注"],...data.transactions.map(x=>[fmtTime(x.date),byId(x.medicineId)?.name,x.batchNo,x.type,x.quantity,x.operator,x.note])]));if(b.dataset.export==="finance")download("收费统计.csv",csv([["时间","处方号","患者","医生","药品","数量","金额","支付方式"],...data.prescriptions.map(x=>[fmtTime(x.date),x.id,x.patient,x.doctor,x.medicineName,x.quantity,x.amount,x.payment])]));if(b.dataset.backup){if(currentUser().role!=="admin")return toast("仅管理员可以下载完整备份");audit("下载备份","导出完整本地数据");download("可瑞康诊所备份.json",JSON.stringify(data,null,2),"application/json")}if(b.dataset.restore){if(currentUser().role!=="admin")return toast("仅管理员可以恢复备份");document.getElementById("restoreFile").click()}});
document.getElementById("restoreFile").onchange=e=>{if(currentUser().role!=="admin")return toast("仅管理员可以恢复备份");const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{data=JSON.parse(reader.result);ensureExtendedData();audit("恢复备份","导入历史备份数据");save();render();toast("备份恢复成功")}catch{toast("备份文件格式不正确")}};reader.readAsText(file)};
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.editMedicine){if(!requirePermission("medicine.create"))return;const m=byId(b.dataset.editMedicine),form=document.getElementById("editMedicineForm");Object.entries({medicineId:m.id,name:m.name,code:m.code,spec:m.spec,unit:m.unit,barcode:m.barcode,salePrice:m.salePrice,minStock:m.minStock,warningDays:m.warningDays}).forEach(([k,v])=>form.elements[k].value=v);openModal("editMedicineModal")}if(b.dataset.toggleMedicine){if(!requirePermission("medicine.create"))return;const m=byId(b.dataset.toggleMedicine);m.disabled=!m.disabled;audit(m.disabled?"停用药品":"启用药品",m.name);save();render();toast(m.disabled?"药品已停用":"药品已启用")}if(b.dataset.open==="settingsModal"){const form=document.getElementById("settingsForm");form.elements.expiryWarningDays.value=data.settings.expiryWarningDays;form.elements.backupReminder.value=String(data.settings.backupReminder)}})
document.getElementById("editMedicineForm").onsubmit=e=>{e.preventDefault();if(!requirePermission("medicine.edit"))return;const v=Object.fromEntries(new FormData(e.target)),m=byId(v.medicineId);Object.assign(m,{name:v.name,code:v.code,spec:v.spec,unit:v.unit||"盒",barcode:v.barcode,salePrice:+v.salePrice,minStock:+v.minStock,warningDays:+v.warningDays});audit("编辑药品档案",m.name);save();render();closeModals();toast("药品档案已更新")};
document.getElementById("settingsForm").onsubmit=e=>{e.preventDefault();if(currentUser().role!=="admin")return toast("仅管理员可以修改系统设置");const v=Object.fromEntries(new FormData(e.target));data.settings.expiryWarningDays=+v.expiryWarningDays;data.settings.backupReminder=v.backupReminder==="true";audit("修改系统设置",`默认效期提醒 ${v.expiryWarningDays} 天`);save();render();closeModals();toast("提醒设置已保存")};
document.getElementById("logoutBtn").onclick=()=>{audit("退出登录","退出系统");if(window.forceSignOutAndShowLogin)return window.forceSignOutAndShowLogin("logout");sessionStorage.removeItem("clinic-login");data.currentUserId="";save();document.getElementById("loginScreen").classList.remove("hidden");setupLogin();toast("已退出登录")};
function setupLogin(){const screen=document.getElementById("loginScreen"),select=document.getElementById("loginUser");select.innerHTML=data.users.filter(x=>x.active).map(x=>`<option value="${x.id}">${x.name}${x.role==="admin"?"（管理员）":""}</option>`).join("");if(window.KERUIKANG_AUTH_SESSION?.shouldForceLogin?.()||sessionStorage.getItem("clinic-login")!=="yes"||!data.currentUserId)screen.classList.remove("hidden");else screen.classList.add("hidden");document.getElementById("loginForm").onsubmit=e=>{e.preventDefault();const lockedUntil=+sessionStorage.getItem("clinic-lock-until")||0;if(Date.now()<lockedUntil)return toast("登录暂时锁定，请稍后重试");const v=Object.fromEntries(new FormData(e.target));if(v.password!=="123456"){const tries=(+sessionStorage.getItem("clinic-login-tries")||0)+1;sessionStorage.setItem("clinic-login-tries",tries);if(tries>=5){sessionStorage.setItem("clinic-lock-until",Date.now()+60000);sessionStorage.setItem("clinic-login-tries",0);return toast("连续输错 5 次，已锁定 1 分钟")}return toast(`密码错误，还可尝试 ${5-tries} 次`)}sessionStorage.removeItem("clinic-login-tries");window.KERUIKANG_AUTH_SESSION?.releaseForceLogin?.();data.currentUserId=v.userId;save();sessionStorage.setItem("clinic-login","yes");screen.classList.add("hidden");render();audit("用户登录","登录系统");if(data.settings.backupReminder&&currentUser().role==="admin")toast("登录成功。建议定期下载完整备份");else toast("登录成功")}}
setupLogin();render();
